# general configs
exclude   : ["README.md", "Rakefile", "changelog.md", "LICENSE", "Procfile", "Gemfile", "config.rb"]
auto      : true
pygments  : true
# Maruku doesn't play nicely with scss syntax in pygments
markdown  : rdiscount
# site info
title     : Venus
tagline   : Where bugs go to die.
# permalinks
permalink : /:categories/:title
# author
author :
  name    : LinkedIn
  github  : sethmcl
  twitter : venus_js
authors :
  sethmcl :
    name  : Seth McLaughlin
    href  : http://www.linkedin.com/in/sethmclaughlin
# The production_url is only used when full-domain names are needed such as sitemap.txt 
production_url : http://www.venusjs.org

## custom configs
# copyright notice
copyright :
  holder  : LinkedIn Corporation
  year    : 2013
# asset management
assets :
  cacheBurst : true
  stylesheets :
    - main
    - venus
  vendor :
    scripts :
      jQuery :
        version : 1.8.2
meta :
  image : 'ASSET_PATH/images/logos/venus_mini_logo.png'
archetype :
  version : 0.0.1.pre.2
lang      : en
# git info
git :
  account : linkedin
  repo    : venus.js
# footer
footer :
  links : 
    - {title : GitHub, url : 'GIT_PATH' }
    - {title : Issue Tracker, url : 'GIT_PATH/issues?state=open' }
    - {title : CHANGELOG, url : 'GIT_PATH/blob/master/CHANGELOG.md' }
    - {title : Contributing, url : 'GIT_PATH/blob/master/CONTRIBUTING.md' }
# pagination
pagination : false

# API docs
#api_docs :
#  - {title: 'Module Methods', url: '/documentation/module/', summary : 'Explore the documentation for mixins and other module methods.' }
#  - {title: 'Native Methods', url: '/documentation/native/', summary : 'Learn about the native methods provided through the Sass function API.' }

# all links will be namespaced by BASE_PATH if defined
BASE_PATH : false

# By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
# ex: [BASE_PATH]/assets/
#
# Override this by defining an absolute path to assets here.
# ex: 
#   http://s3.amazonaws.com/yoursite/themes/watermelon/assets
ASSET_PATH : false

# some native pages
archive_path    : /archive.html
categories_path : /categories.html
tags_path       : /tags.html

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
comments :
  provider : false
  # provider : livefyre
  # livefyre :
    # site_id : 313052

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-36360221-1'

search :
  provider : false
  # provider : tapir
  # tapir :
    # token : TBD
